"""
Client for the ai-services microservice.

Calls out over HTTP to AI_SERVICES_URL (set to the ai-services container's
address in infra/docker-compose.yml). If ai-services isn't reachable — e.g.
running the backend standalone for a quick demo — falls back to an inline
copy of the same stub logic so the booking flow still works end-to-end
without requiring every service to be up.
"""
from __future__ import annotations

import os

import httpx

AI_SERVICES_URL = os.environ.get("AI_SERVICES_URL", "http://127.0.0.1:8001")
# 127.0.0.1, not "localhost" — on Windows, httpx/asyncio resolving "localhost"
# tries IPv6 (::1) first and only falls back to IPv4 after it times out, which
# measured ~2s of pure connection delay per call. Skip the DNS ambiguity.

# A single shared, keep-alive client rather than the httpx.post() shortcut,
# which opens and tears down a fresh connection on every call — that alone
# measured ~1s of pure per-call overhead, doubled for /chat (two calls:
# classify + compose). Reusing one pooled client amortizes that away.
_client = httpx.Client(base_url=AI_SERVICES_URL, timeout=3.0)


def generate_contract(
    *,
    artist_name: str,
    organizer_name: str,
    event_title: str,
    event_date: str,
    fee_zar: float,
    city: str = "",
) -> dict:
    payload = {
        "artist_name": artist_name,
        "organizer_name": organizer_name,
        "event_title": event_title,
        "event_date": event_date,
        "fee_zar": fee_zar,
        "city": city,
    }
    try:
        resp = _client.post("/contracts/generate", json=payload)
        resp.raise_for_status()
        return resp.json()
    except (httpx.HTTPError, httpx.TimeoutException):
        return _fallback_contract(**payload)


def _fallback_contract(
    artist_name: str, organizer_name: str, event_title: str, event_date: str, fee_zar: float, city: str = ""
) -> dict:
    """STUB fallback — mirrors ai-services/services/contracts.py's mocked
    output shape so callers never see a different contract shape depending
    on whether ai-services is reachable."""
    risk_flags = []
    risk_score = 0.05
    if fee_zar < 500:
        risk_flags.append("Fee is below typical market floor for a booked performance")
        risk_score += 0.3
    contract_text = (
        f"PERFORMANCE AGREEMENT\n\nBetween {organizer_name} (\"Organizer\") and {artist_name} (\"Artist\").\n"
        f"Event: {event_title} on {event_date}{f' in {city}' if city else ''}.\n"
        f"Agreed fee: R{fee_zar:,.2f}, held in escrow and released on milestone confirmation.\n\n"
        "[Generated by local fallback stub — ai-services was unreachable]"
    )
    return {
        "contract_text": contract_text,
        "risk_score": round(min(risk_score, 0.99), 2),
        "risk_flags": risk_flags,
        "market_rate_note": "ai-services unreachable — fallback estimate only.",
    }


def classify_chat_intent(message: str) -> dict:
    try:
        resp = _client.post("/chat/classify", json={"message": message})
        resp.raise_for_status()
        return resp.json()
    except (httpx.HTTPError, httpx.TimeoutException):
        return {"intent": "general", "detected_language": "en", "confidence": 0.0}


def compose_chat_reply(intent: str, user_name: str, data: dict) -> str:
    try:
        resp = _client.post("/chat/compose", json={"intent": intent, "user_name": user_name, "data": data})
        resp.raise_for_status()
        return resp.json()["reply"]
    except (httpx.HTTPError, httpx.TimeoutException):
        first_name = user_name.split(" ")[0] if user_name else "there"
        return f"Hi {first_name} — I'm having trouble reaching the assistant right now, try again in a moment."


def estimate_tax(*, gross_income_zar: float, expenses_zar: float, period_start: str, period_end: str) -> dict:
    """AI Tax Assistant — see routers/wallet.py, which calls this with the
    artist's real earnings (summed from the payments ledger), not a
    hardcoded figure."""
    payload = {
        "gross_income_zar": gross_income_zar,
        "expenses_zar": expenses_zar,
        "period_start": period_start,
        "period_end": period_end,
    }
    try:
        resp = _client.post("/tax/estimate", json=payload)
        resp.raise_for_status()
        return resp.json()
    except (httpx.HTTPError, httpx.TimeoutException):
        return _fallback_tax_estimate(**payload)


def _fallback_tax_estimate(gross_income_zar: float, expenses_zar: float, period_start: str, period_end: str) -> dict:
    """STUB fallback — a much-simplified flat-rate estimate, used only if
    ai-services is unreachable (mirrors ai-services/services/tax.py's
    response shape so the Wallet page never sees a different shape)."""
    taxable = max(gross_income_zar - expenses_zar, 0)
    tax = round(taxable * 0.18, 2)  # flat 18% — real estimate uses ai-services' bracket table
    return {
        "taxable_income_zar": round(taxable, 2),
        "estimated_tax_zar": tax,
        "effective_rate_pct": round((tax / taxable * 100) if taxable else 0, 2),
        "sars_filing_due": "2027-01-31",
        "categorized_expenses": {},
        "note": "ai-services unreachable — flat-rate fallback estimate only.",
    }
