"""
AI Contract Generator + Risk Scoring.

Production design: an LLM with retrieval-augmented generation (LangChain +
OpenAI API) grounded in a vetted South African entertainment/labour-law
clause library, drafting a fair contract from a template and benchmarking
the agreed fee against market-rate data, then emitting a 0-1 risk score
plus a list of flagged/missing clauses.

STUB: this module assembles a templated contract string and a rule-based
risk score locally — no LLM call is made. Swap `generate_contract` for a
RAG pipeline call when the clause library + model are wired in.
"""
from __future__ import annotations

from pydantic import BaseModel

STANDARD_CLAUSES = [
    "Performance date, time and venue as specified in the booking",
    "Agreed fee and payment schedule (held in escrow until milestone confirmation)",
    "Cancellation and force majeure terms",
    "Equipment and technical rider responsibilities",
    "Image/recording usage rights",
    "Dispute resolution process",
]


class ContractRequest(BaseModel):
    artist_name: str
    organizer_name: str
    event_title: str
    event_date: str
    fee_zar: float
    city: str = ""
    include_recording_rights: bool = True


class ContractResponse(BaseModel):
    contract_text: str
    risk_score: float  # 0.00 (low risk) - 1.00 (high risk)
    risk_flags: list[str]
    market_rate_note: str


def generate_contract(req: ContractRequest) -> ContractResponse:
    """STUB: mocked RAG generation. Produces a deterministic templated
    contract and a rule-based risk score standing in for the real
    LLM + clause-library pipeline."""
    clauses = list(STANDARD_CLAUSES)
    if not req.include_recording_rights:
        clauses.remove("Image/recording usage rights")

    contract_text = (
        f"PERFORMANCE AGREEMENT\n\n"
        f"Between {req.organizer_name} (\"Organizer\") and {req.artist_name} (\"Artist\").\n"
        f"Event: {req.event_title} on {req.event_date}"
        f"{f' in {req.city}' if req.city else ''}.\n"
        f"Agreed fee: R{req.fee_zar:,.2f}, held in escrow and released on milestone confirmation.\n\n"
        "Clauses:\n" + "\n".join(f"  {i+1}. {c}" for i, c in enumerate(clauses)) +
        "\n\nGenerated by Fimiya AI Contract Generator (stub) — for legal review before signature."
    )

    risk_flags: list[str] = []
    risk_score = 0.05
    if req.fee_zar < 500:
        risk_flags.append("Fee is below typical market floor for a booked performance")
        risk_score += 0.3
    if not req.include_recording_rights:
        risk_flags.append("No recording/image usage clause — ambiguous rights if content is published")
        risk_score += 0.15
    if not req.city:
        risk_flags.append("Venue city not specified")
        risk_score += 0.1

    market_rate_note = (
        f"R{req.fee_zar:,.2f} is within the modelled market range for this event type (stub benchmark)."
        if req.fee_zar >= 500
        else "Fee flagged as below the modelled market range (stub benchmark)."
    )

    return ContractResponse(
        contract_text=contract_text,
        risk_score=round(min(risk_score, 0.99), 2),
        risk_flags=risk_flags,
        market_rate_note=market_rate_note,
    )
